# Generated by Django 4.2.5 on 2023-09-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                (
                    "years_of_experience",
                    models.FloatField(verbose_name="Date of Birth"),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[("it", "IT"), ("hr", "HR"), ("finance", "Finance")],
                        max_length=10,
                        verbose_name="Department",
                    ),
                ),
                ("resume", models.FileField(upload_to="", verbose_name="Resume")),
            ],
            options={
                "verbose_name": "Candidate",
                "verbose_name_plural": "Candidate",
            },
        ),
    ]
